# Generated by Django 5.1.4 on 2024-12-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property_lettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
    ]
