name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 1) Build a "test" image (not pushed yet).
      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/myapp:test

      # 2) Run your test suite inside that "test" image.
      - name: Run tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/myapp:test \
            /bin/bash -c "coverage run -m pytest --maxfail=1 --disable-warnings && coverage report --fail-under=80"

      # 3) If tests pass, build & push the final "latest" image to Docker Hub
      - name: Build & Push final image
        if: success()
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myapp:latest

  deploy:
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DOCKER_DROPLET_IP }}
          username: root
          key: ${{ secrets.DOCKER_DROPLET_SSH_KEY }}
          script: |
            # Log in to Docker Hub on the Droplet
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            # Pull the newly built image
            docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
            
            # Stop & remove any existing container
            docker stop myapp_container || true
            docker rm myapp_container || true
            
            # Run the new container on port 8001
            docker run -d -p 8001:8000 --name myapp_container ${{ secrets.DOCKER_USERNAME }}/myapp:latest
